### PR TITLE
Handle the scenario of rerun this role on up and running hosted engine environment

### LINKED ISSUE #37: Need to handle the scenario of running this role on deployed environment
Need to handle the scenario of running this role on deployed environment 

IMHO we should skip with an error message something like:
"This environment already deployed, to be able to redeploy please run the command ovirt-hosted-engine-cleanup  command on the <host>"

In my case the environment destroyed partially and I got the following error:
TASK [oVirt.hosted-engine-setup : Fail if user chose more memory then the available memory] ************************************************************************************************************************************************
task path: /tmp/ovirt-ansible-hosted-engine-setup/tasks/pre_checks/validate_memory_size.yml:35
Wednesday 05 December 2018  15:34:57 +0200 (0:00:00.045)       0:02:42.445 ****
fatal: [automation-xxx.yyy.com]: FAILED! => {
    "changed": false,
    "msg": "Not enough memory: 12288MB, while only 9740MB are available on the host"
}

### PR DESCRIPTION
**Pull request by kobihk**
Fixes #37

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by kobihk** [comment]
@tiraboschi, @irosenzw,
Could you please review this patch
Thanks,
   Kobi

**Comment by sandrobonazzola** [comment]
can you please rebase?

**Comment by eslutsky** [comment]
most of this change is not relevant to the latest code,
so it needs a serious rebase.
for clarity it's better to use `hosted-engine --vm-status` to check the status before failing.

**Pull request closed without merging**
