### PR TITLE
Fix variable gathering

### PR DESCRIPTION
**Pull request by tiraboschi**
Fixes: https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/issues/203

### CODE REVIEW

**Comment by kostas-rs** [comment]
Hi guys, since you are looking to fix this instance of the issue in the `tasks/fetch_host_ip.yml` file i found out that same issue occurs in other places in the role. Below are the ones i found (although there might be other places too depending on the flow):

```
tasks/pre_checks/define_variables.yml
tasks/pre_checks/001_validate_network_interfaces.yml
tasks/pre_checks/validate_gateway.yml he_gateway
tasks/bootstrap_local_vm/01_prepare_routing_rules.yml
tasks/bootstrap_local_vm/04_engine_final_tasks.yml
```

Thank you

**Comment by tiraboschi** [comment]
@kostas-rs can you please also report the line of the issue for that files?

**Comment by tiraboschi** [comment]
This specific issue happens only if we have set_facts and/or register with a when on the same task

**Comment by kostas-rs** [comment]
Here are the instances i found:

- https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/define_variables.yml#L13

- https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/001_validate_network_interfaces.yml#L52

- https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/001_validate_network_interfaces.yml#L64

- https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/validate_gateway.yml#L23

- https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml#L38

- https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml#L90

- https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml#L97

- https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/04_engine_final_tasks.yml#L18

**Comment by tiraboschi** [comment]
> Here are the instances i found:
> 
> * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/define_variables.yml#L13

This one is inside a block so it should be fine

> * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/001_validate_network_interfaces.yml#L52

No issue here

> * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/001_validate_network_interfaces.yml#L64

same

> * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/validate_gateway.yml#L23

maybe this

> * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml#L38

route_rules_ipv6 is not a user set variable, no collision risk here

> * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml#L90

same

> * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml#L97

same

> * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/04_engine_final_tasks.yml#L18

same

**Comment by tiraboschi** [comment]
Te issue comes from here:
```
[stirabos@t470s ~]$ cat test.yml 
---
- name: test
  hosts: localhost
  connection: local
  tasks:
    - name: Get full hostname
      command: hostname -f
      changed_when: true
      register: host_full_name
    - name: Define he_host_name if not defined
      set_fact:
        he_host_name: "{{ host_full_name.stdout_lines[0] }}"
      register: he_host_name
    - debug: var=he_host_name
    - name: Define he_host_name if not defined
      set_fact:
        he_host_name: "{{ host_full_name.stdout_lines[0] }}"
      register: he_host_name
      when: false
    - debug: var=he_host_name
[stirabos@t470s ~]$ ansible-playbook -i localhost, test.yml 

PLAY [test] ******************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Get full hostname] *****************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Define he_host_name if not defined] ************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *****************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "he_host_name": "t470s.localdomain"
}

TASK [Define he_host_name if not defined] ************************************************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [debug] *****************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "he_host_name": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```

register overwrite set_facts on skipped tasks.

**Comment by kostas-rs** [comment]
Hi @tiraboschi, thank you for looking into the above.
Just to provide some more assistance i ran the playbook again and captured the debug for the above:

> > Here are the instances i found:
> > 
> > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/define_variables.yml#L13
> 
> This one is inside a block so it should be fine

```
2019-05-31 09:25:24,153 p=13009 u=user |  TASK [ovirt.hosted_engine_setup : debug] ***************************************************************************************************************************************************
2019-05-31 09:25:24,153 p=13009 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/pre_checks/define_variables.yml:15
2019-05-31 09:25:24,153 p=13009 u=user |  ok: [node-01.example.com] => {
    "he_cloud_init_domain_name": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
```

> > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/001_validate_network_interfaces.yml#L52
> 
> No issue here

```
2019-05-31 09:25:27,774 p=13009 u=user |  TASK [ovirt.hosted_engine_setup : debug] ***************************************************************************************************************************************************
2019-05-31 09:25:27,775 p=13009 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/pre_checks/001_validate_network_interfaces.yml:53
2019-05-31 09:25:27,775 p=13009 u=user |  ok: [node-01.example.com] => {
    "valid_network_interfaces": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": "lo",
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "changed": false,
                "iface_item": "lo",
                "skip_reason": "Conditional result was False",
                "skipped": true
            },
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": "wlp5s0",
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "changed": false,
                "iface_item": "wlp5s0",
                "skip_reason": "Conditional result was False",
                "skipped": true
            },
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": "p3p2",
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "changed": false,
                "iface_item": "p3p2",
                "skip_reason": "Conditional result was False",
                "skipped": true
            },
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": "p3p1",
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "ansible_facts": {
                    "bond_valid_name": "",
                    "otopi_net_host": "p3p1",
                    "type": "ether"
                },
                "changed": false,
                "failed": false,
                "iface_item": "p3p1"
            }
        ]
    }
}
```

> > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/001_validate_network_interfaces.yml#L64
> 
> same
 
```
2019-05-31 09:25:28,002 p=13009 u=user |  TASK [ovirt.hosted_engine_setup : debug] ***************************************************************************************************************************************************
2019-05-31 09:25:28,003 p=13009 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/pre_checks/001_validate_network_interfaces.yml:65
2019-05-31 09:25:28,005 p=13009 u=user |  ok: [node-01.example.com] => {
    "bb_filtered_list": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": {
                    "_ansible_ignore_errors": null,
                    "_ansible_item_label": "lo",
                    "_ansible_item_result": true,
                    "_ansible_no_log": false,
                    "changed": false,
                    "iface_item": "lo",
                    "skip_reason": "Conditional result was False",
                    "skipped": true
                },
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "bond_item": {
                    "_ansible_ignore_errors": null,
                    "_ansible_item_label": "lo",
                    "_ansible_item_result": true,
                    "_ansible_no_log": false,
                    "changed": false,
                    "iface_item": "lo",
                    "skip_reason": "Conditional result was False",
                    "skipped": true
                },
                "changed": false,
                "skip_reason": "Conditional result was False",
                "skipped": true
            },
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": {
                    "_ansible_ignore_errors": null,
                    "_ansible_item_label": "wlp5s0",
                    "_ansible_item_result": true,
                    "_ansible_no_log": false,
                    "changed": false,
                    "iface_item": "wlp5s0",
                    "skip_reason": "Conditional result was False",
                    "skipped": true
                },
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "bond_item": {
                    "_ansible_ignore_errors": null,
                    "_ansible_item_label": "wlp5s0",
                    "_ansible_item_result": true,
                    "_ansible_no_log": false,
                    "changed": false,
                    "iface_item": "wlp5s0",
                    "skip_reason": "Conditional result was False",
                    "skipped": true
                },
                "changed": false,
                "skip_reason": "Conditional result was False",
                "skipped": true
            },
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": {
                    "_ansible_ignore_errors": null,
                    "_ansible_item_label": "p3p2",
                    "_ansible_item_result": true,
                    "_ansible_no_log": false,
                    "changed": false,
                    "iface_item": "p3p2",
                    "skip_reason": "Conditional result was False",
                    "skipped": true
                },
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "bond_item": {
                    "_ansible_ignore_errors": null,
                    "_ansible_item_label": "p3p2",
                    "_ansible_item_result": true,
                    "_ansible_no_log": false,
                    "changed": false,
                    "iface_item": "p3p2",
                    "skip_reason": "Conditional result was False",
                    "skipped": true
                },
                "changed": false,
                "skip_reason": "Conditional result was False",
                "skipped": true
            },
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": {
                    "_ansible_ignore_errors": null,
                    "_ansible_item_label": "p3p1",
                    "_ansible_item_result": true,
                    "_ansible_no_log": false,
                    "ansible_facts": {
                        "bond_valid_name": "",
                        "otopi_net_host": "p3p1",
                        "type": "ether"
                    },
                    "changed": false,
                    "failed": false,
                    "iface_item": "p3p1"
                },
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "ansible_facts": {
                    "net_iface": {
                        "_ansible_ignore_errors": null,
                        "_ansible_item_label": "p3p1",
                        "_ansible_item_result": true,
                        "_ansible_no_log": false,
                        "ansible_facts": {
                            "bond_valid_name": "",
                            "otopi_net_host": "p3p1",
                            "type": "ether"
                        },
                        "changed": false,
                        "failed": false,
                        "iface_item": "p3p1"
                    }
                },
                "bond_item": {
                    "_ansible_ignore_errors": null,
                    "_ansible_item_label": "p3p1",
                    "_ansible_item_result": true,
                    "_ansible_no_log": false,
                    "ansible_facts": {
                        "bond_valid_name": "",
                        "otopi_net_host": "p3p1",
                        "type": "ether"
                    },
                    "changed": false,
                    "failed": false,
                    "iface_item": "p3p1"
                },
                "changed": false,
                "failed": false
            }
        ]
    }
}
```

> > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/validate_gateway.yml#L23
> 
> maybe this

```
2019-05-31 09:25:32,938 p=13009 u=user |  TASK [ovirt.hosted_engine_setup : debug] ***************************************************************************************************************************************************
2019-05-31 09:25:32,939 p=13009 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/pre_checks/validate_gateway.yml:25
2019-05-31 09:25:32,939 p=13009 u=user |  ok: [node-01.example.com] => {
    "he_gateway": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
```

> > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml#L38
> 
> route_rules_ipv6 is not a user set variable, no collision risk here

```
2019-05-31 09:25:59,892 p=13009 u=user |  TASK [ovirt.hosted_engine_setup : debug] ***************************************************************************************************************************************************
2019-05-31 09:25:59,893 p=13009 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml:42
2019-05-31 09:25:59,894 p=13009 u=user |  ok: [node-01.example.com] => {
    "route_rules_ipv6": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
```

> > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml#L90
> 
> same

```
2019-05-31 09:26:03,864 p=13009 u=user |  TASK [ovirt.hosted_engine_setup : debug] ***************************************************************************************************************************************************
2019-05-31 09:26:03,866 p=13009 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml:94
2019-05-31 09:26:03,866 p=13009 u=user |  ok: [node-01.example.com] => {
    "result": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
```

> > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml#L97
> 
> same

```
2019-05-31 09:54:53,011 p=13571 u=kostas |  TASK [ovirt.hosted_engine_setup : debug] *************************************************************************************************************************************************************************
2019-05-31 09:54:53,011 p=13571 u=kostas |  task path: /Users/kostas/.ansible/roles/ovirt.hosted_engine_setup/tasks/bootstrap_local_vm/01_prepare_routing_rules.yml:102
2019-05-31 09:54:53,012 p=13571 u=kostas |  ok: [ovirt-node-01.ops.recordsure.com] => {
    "result": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
```

> > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/bootstrap_local_vm/04_engine_final_tasks.yml#L18
> 
> same

```
2019-05-31 09:41:50,647 p=13009 u=user |  TASK [ovirt.hosted_engine_setup : debug] ***************************************************************************************************************************************************
2019-05-31 09:41:50,647 p=13009 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/bootstrap_local_vm/04_engine_final_tasks.yml:21
2019-05-31 09:41:50,648 p=13009 u=user |  ok: [node-01.example.com -> engine.example.com] => {
    "libgfapi_support_out": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
```

Hope this helps, thank you.

**Comment by tiraboschi** [comment]
> Hi @tiraboschi, thank you for looking into the above.
> Just to provide some more assistance i ran the playbook again and captured the debug for the above:
> 
> > > Here are the instances i found:
> > > 
> > > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/define_variables.yml#L13
> > 
> > 
> > This one is inside a block so it should be fine
> 
> ```
> 2019-05-31 09:25:24,153 p=13009 u=user |  TASK [ovirt.hosted_engine_setup : debug] ***************************************************************************************************************************************************
> 2019-05-31 09:25:24,153 p=13009 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/pre_checks/define_variables.yml:15
> 2019-05-31 09:25:24,153 p=13009 u=user |  ok: [node-01.example.com] => {
>     "he_cloud_init_domain_name": {
>         "changed": false,
>         "skip_reason": "Conditional result was False",
>         "skipped": true
>     }
> }
> ```

OK, right, thanks.

> > > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/001_validate_network_interfaces.yml#L52
> > 
> > 
> > No issue here
> 
> ```
> 2019-05-31 09:25:27,774 p=13009 u=user |  TASK [ovirt.hosted_engine_setup : debug] ***************************************************************************************************************************************************
> 2019-05-31 09:25:27,775 p=13009 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/pre_checks/001_validate_network_interfaces.yml:53
> 2019-05-31 09:25:27,775 p=13009 u=user |  ok: [node-01.example.com] => {
>     "valid_network_interfaces": {
>         "changed": false,
>         "msg": "All items completed",
>         "results": [
>             {
>                 "_ansible_ignore_errors": null,
>                 "_ansible_item_label": "lo",
>                 "_ansible_item_result": true,
>                 "_ansible_no_log": false,
>                 "changed": false,
>                 "iface_item": "lo",
>                 "skip_reason": "Conditional result was False",
>                 "skipped": true
>             },
>             {
>                 "_ansible_ignore_errors": null,
>                 "_ansible_item_label": "wlp5s0",
>                 "_ansible_item_result": true,
>                 "_ansible_no_log": false,
>                 "changed": false,
>                 "iface_item": "wlp5s0",
>                 "skip_reason": "Conditional result was False",
>                 "skipped": true
>             },
>             {
>                 "_ansible_ignore_errors": null,
>                 "_ansible_item_label": "p3p2",
>                 "_ansible_item_result": true,
>                 "_ansible_no_log": false,
>                 "changed": false,
>                 "iface_item": "p3p2",
>                 "skip_reason": "Conditional result was False",
>                 "skipped": true
>             },
>             {
>                 "_ansible_ignore_errors": null,
>                 "_ansible_item_label": "p3p1",
>                 "_ansible_item_result": true,
>                 "_ansible_no_log": false,
>                 "ansible_facts": {
>                     "bond_valid_name": "",
>                     "otopi_net_host": "p3p1",
>                     "type": "ether"
>                 },
>                 "changed": false,
>                 "failed": false,
>                 "iface_item": "p3p1"
>             }
>         ]
>     }
> }
> ```

Yes, but this is needed to loop over result: https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/001_validate_network_interfaces.yml#L61

> > > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/001_validate_network_interfaces.yml#L64
> > 
> > 
> > same
> 
> ```
> 2019-05-31 09:25:28,002 p=13009 u=user |  TASK [ovirt.hosted_engine_setup : debug] ***************************************************************************************************************************************************
> 2019-05-31 09:25:28,003 p=13009 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/pre_checks/001_validate_network_interfaces.yml:65
> 2019-05-31 09:25:28,005 p=13009 u=user |  ok: [node-01.example.com] => {
>     "bb_filtered_list": {
>         "changed": false,
>         "msg": "All items completed",
>         "results": [

same:
https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/master/tasks/pre_checks/001_validate_network_interfaces.yml#L69

> > > * https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/pre_checks/validate_gateway.yml#L23
> > 
> > 
> > maybe this

done

> 
> Some of the above are network related and i noticed that they are causing misc issues like no default route is set in the ovirt-engine VM.
> 
> Hope this helps, thank you.

**Pull request merged**
