### PR TITLE
Remove libvirt default network leftover

### PR DESCRIPTION
**Pull request by almusil**
Remove libvirt default network that was temorarely used
for bootstrap vm.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by almusil** [comment]
ci add to whitelist

**Comment by almusil** [comment]
Related to #79

**Comment by irosenzw** [comment]
@almusil  did you verified it ?

**Comment by almusil** [comment]
Not yet I need the CI build to run it locally

**Comment by irosenzw** [comment]
@almusil please resolve the conflicts and push again

**Comment by almusil** [comment]
@irosenzw Done

**Comment by tiraboschi** [comment]
ci please build

**Comment by tiraboschi** [comment]
Verified on https://jenkins.ovirt.org/view/oVirt%20system%20tests/job/ovirt-system-tests_manual/5406/console

**Pull request merged**
