### PR TITLE
another try with serial console

### PR DESCRIPTION
**Pull request by tiraboschi**

### CODE REVIEW

**Comment by irosenzw** [comment]
Did you verify this patch?

**Comment by tiraboschi** [comment]
ci please test

**Comment by tiraboschi** [comment]
> Did you verify this patch?

yes:

```
[ INFO  ] Generating answer file '/var/lib/ovirt-hosted-engine-setup/answers/answers-20190208180347.conf'
[ INFO  ] Generating answer file '/etc/ovirt-hosted-engine/answers.conf'
[ INFO  ] Stage: Pre-termination
[ INFO  ] Stage: Termination
[ INFO  ] Hosted Engine successfully deployed
You have new mail in /var/spool/mail/root
[root@c76he20190208h1 ~]# hosted-engine --console
The engine VM is running on this host
Escape character is ^]

CentOS Linux 7 (Core)
Kernel 3.10.0-957.5.1.el7.x86_64 on an x86_64

enginevm login: 
```

Yes, although to be fully honest also what we had before was "often" working for me.
The point is just if this is rock solid!

**Comment by tiraboschi** [comment]
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1628836
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1660560

**Pull request merged**
